// components/ts/react/Header.tsx
import React from 'react';
import Table from './tags/Table';


interface HeaderProps
{
    logotype ? : string;
}


function Header( props : HeaderProps ) : React.JSX.Element
{
    const name = process.env.VITE_APP_NAME;
    const logotype = props.logotype || 'https://raw.githubusercontent.com/capsulescodes/inertia-mailable/main/art/capsules-inertia-mailable-logotype.png';


    return (

        <Table className="p-12 text-center">

            <img src={ logotype } className="w-12 max-h-12 mb-3" alt={ name } />

            <a href={ name } className="block text-lg font-bold no-underline text-slate-600">{ name }</a>

        </Table>

    );
};


export default Header;

// components/ts/vue/Header.vue
<script setup lang="ts">

import Table from './tags/Table.vue';


interface HeaderProps
{
	logotype ? : string;
}


const props = defineProps<HeaderProps>();


const name = import.meta.env.VITE_APP_NAME;
const logotype = props.logotype ?? 'https://raw.githubusercontent.com/capsulescodes/inertia-mailable/main/art/capsules-inertia-mailable-logotype.png';

</script>

<template>

	<Table class="p-12 text-center">

		<img v-bind:src="logotype" class="w-12 max-h-12 mb-3" v-bind:alt="name">

		<a v-bind:href="name" class="block text-lg font-bold no-underline text-slate-600" v-text="name" />

	</Table>

</template>
