// components/js/react/tags/Table.jsx
import React from 'react';


function Table( { className = "", align = 'center', width = '100%', cellpadding = '0', cellspacing = '0', role = 'presentation', children } )
{
	return (
		<table className={ className } align={ align } width={ width } cellPadding={ cellpadding } cellSpacing={ cellspacing } role={ role }>

			<tr>

				<td>{ children }</td>

			</tr>

		</table>
	);
};


export default Table;

// components/vue/tags/Table.vue
<script setup lang="ts">

interface TableProps
{
    width ? : string;
    cellpadding ? : string;
    cellspacing ? : string;
    role ? : string;
}


const props = defineProps<TableProps>();

</script>

<template>

<table
    v-bind:width="props.width ?? '100%'"
    v-bind:cellpadding="props.cellpadding ?? '0'"
    v-bind:cellspacing="props.cellspacing ?? '0'"
    v-bind:role="props.role ?? 'presentation'"
>

    <tr>

        <td>

            <slot />

        </td>

    </tr>

</table>

</template>
